### ISSUE TITLE
remove (or hide) results table below tag cloud

### ISSUE THREAD

**Issue by lukewendling** [Sotera/GEQE#48]
![image](https://cloud.githubusercontent.com/assets/12628/10645527/cac32144-77f3-11e5-9aaf-f630a405d320.png)

**Comment by jhughes13** [comment]
Build 49-sort-graph: word cloud and term list are no longer visible when user clicks on cluster pin.

**Comment by jhughes13** [comment]
Verified on master branch.  Term list is no longer visible; word cloud is present for location and event based jobs.
